# Generated by Django 5.2.5 on 2025-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("food_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("caloric_value", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("saturated_fats", models.FloatField(blank=True, null=True)),
                ("monounsaturated_fats", models.FloatField(blank=True, null=True)),
                ("polyunsaturated_fats", models.FloatField(blank=True, null=True)),
                ("carbohydrates", models.FloatField(blank=True, null=True)),
                ("sugars", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("cholesterol", models.FloatField(blank=True, null=True)),
                ("sodium", models.FloatField(blank=True, null=True)),
                ("water", models.FloatField(blank=True, null=True)),
                ("nutrition_density", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
