# Generated by Django 5.2.5 on 2025-10-03 13:41


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
                'db_table': 'allergen',
            },
        ),
        migrations.CreateModel(
            name='NCDQuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('question_ms', models.TextField(blank=True, null=True)),
                ('question_zh', models.TextField(blank=True, null=True)),
                ('question_vi', models.TextField(blank=True, null=True)),
                ('option_a', models.TextField()),
                ('option_a_ms', models.TextField(blank=True, null=True)),
                ('option_a_zh', models.TextField(blank=True, null=True)),
                ('option_a_vi', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField()),
                ('option_b_ms', models.TextField(blank=True, null=True)),
                ('option_b_zh', models.TextField(blank=True, null=True)),
                ('option_b_vi', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField()),
                ('option_c_ms', models.TextField(blank=True, null=True)),
                ('option_c_zh', models.TextField(blank=True, null=True)),
                ('option_c_vi', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField()),
                ('option_d_ms', models.TextField(blank=True, null=True)),
                ('option_d_zh', models.TextField(blank=True, null=True)),
                ('option_d_vi', models.TextField(blank=True, null=True)),
                ('correct_option', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'NCD Quiz Question',
                'verbose_name_plural': 'NCD Quiz Questions',
                'db_table': 'ncd_quiz_question',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPhysicalChallenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=500)),
                ('challenge_ms', models.CharField(blank=True, max_length=500, null=True)),
                ('challenge_zh', models.CharField(blank=True, max_length=500, null=True)),
                ('challenge_vi', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Weekly Physical Challenge',
                'verbose_name_plural': 'Weekly Physical Challenges',
                'db_table': 'weekly_physical_challenge',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_ms_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_vi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_zh_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('veg_class', models.CharField(max_length=255)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('carbohydrate_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('calories_kcal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'db_table': 'dish',
                'unique_together': {('dish_name', 'image_url')},
            },
        ),
        migrations.CreateModel(
            name='NCDDeathStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=128)),
                ('cause', models.CharField(db_index=True, max_length=256)),
                ('number_of_deaths', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_of_deaths', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'db_table': 'ncd_death_stat',
                'indexes': [models.Index(fields=['year', 'location'], name='ncd_death_s_year_5d058f_idx'), models.Index(fields=['location', 'cause'], name='ncd_death_s_locatio_2f3a64_idx')],
                'unique_together': {('year', 'location', 'cause')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_heading', models.CharField(max_length=200)),
                ('major_heading_ms', models.CharField(blank=True, max_length=200)),
                ('major_heading_cn', models.CharField(blank=True, max_length=200)),
                ('major_heading_vn', models.CharField(blank=True, max_length=200)),
                ('activity_code', models.IntegerField(db_index=True, unique=True)),
                ('met_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_description_ms', models.CharField(blank=True, max_length=500)),
                ('activity_description_cn', models.CharField(blank=True, max_length=500)),
                ('activity_description_vn', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Physical Activity',
                'verbose_name_plural': 'Physical Activities',
                'db_table': 'physical_activity',
                'indexes': [models.Index(fields=['major_heading'], name='physical_ac_major_h_c49cf4_idx'), models.Index(fields=['activity_description'], name='physical_ac_activit_eb77ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='AllergenDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaa_app.allergen')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaa_app.dish')),
            ],
            options={
                'verbose_name': 'Allergen Dish',
                'verbose_name_plural': 'Allergen Dishes',
                'db_table': 'allergen_dish',
                'unique_together': {('dish', 'allergen')},
            },
        ),
    ]
