# Generated by Django 5.2.5 on 2025-09-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                ("allergen_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergen_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Allergen",
                "verbose_name_plural": "Allergens",
                "db_table": "allergen",
            },
        ),
        migrations.CreateModel(
            name="NCDQuizQuestion",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=255)),
                ("question", models.CharField(max_length=1000)),
                (
                    "question_ms",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "question_zh",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "question_vi",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("option_a", models.CharField(max_length=500)),
                ("optiona_ms", models.CharField(blank=True, max_length=500, null=True)),
                ("optiona_zh", models.CharField(blank=True, max_length=500, null=True)),
                ("optiona_vi", models.CharField(blank=True, max_length=500, null=True)),
                ("option_b", models.CharField(max_length=500)),
                ("optionb_ms", models.CharField(blank=True, max_length=500, null=True)),
                ("optionb_zh", models.CharField(blank=True, max_length=500, null=True)),
                ("optionb_vi", models.CharField(blank=True, max_length=500, null=True)),
                ("option_c", models.CharField(max_length=500)),
                ("optionc_ms", models.CharField(blank=True, max_length=500, null=True)),
                ("optionc_zh", models.CharField(blank=True, max_length=500, null=True)),
                ("optionc_vi", models.CharField(blank=True, max_length=500, null=True)),
                ("option_d", models.CharField(max_length=500)),
                ("optiond_ms", models.CharField(blank=True, max_length=500, null=True)),
                ("optiond_zh", models.CharField(blank=True, max_length=500, null=True)),
                ("optiond_vi", models.CharField(blank=True, max_length=500, null=True)),
                ("correct_option", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "NCD Quiz Question",
                "verbose_name_plural": "NCD Quiz Questions",
                "db_table": "ncd_quiz_question",
            },
        ),
        migrations.CreateModel(
            name="WeeklyPhysicalChallenge",
            fields=[
                ("challenge_id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge", models.CharField(max_length=500)),
                (
                    "challenge_ms",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "challenge_zh",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "challenge_vi",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Weekly Physical Challenge",
                "verbose_name_plural": "Weekly Physical Challenges",
                "db_table": "weekly_physical_challenge",
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("dish_id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_name", models.CharField(max_length=255)),
                (
                    "dish_ms_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dish_vi_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dish_zh_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_url", models.CharField(max_length=255)),
                ("ingredients", models.CharField(max_length=255)),
                ("veg_class", models.CharField(max_length=255)),
                ("fat_g", models.DecimalField(decimal_places=1, max_digits=7)),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=7)),
                ("carbohydrate_g", models.DecimalField(decimal_places=1, max_digits=7)),
                ("calories_kcal", models.IntegerField()),
            ],
            options={
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
                "db_table": "dish",
                "unique_together": {("dish_name", "image_url")},
            },
        ),
        migrations.CreateModel(
            name="PhysicalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_heading", models.CharField(max_length=200)),
                ("major_heading_ms", models.CharField(blank=True, max_length=200)),
                ("major_heading_cn", models.CharField(blank=True, max_length=200)),
                ("major_heading_vn", models.CharField(blank=True, max_length=200)),
                ("activity_code", models.IntegerField(db_index=True, unique=True)),
                ("met_value", models.DecimalField(decimal_places=2, max_digits=5)),
                ("activity_description", models.CharField(max_length=500)),
                (
                    "activity_description_ms",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "activity_description_cn",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "activity_description_vn",
                    models.CharField(blank=True, max_length=500),
                ),
            ],
            options={
                "verbose_name": "Physical Activity",
                "verbose_name_plural": "Physical Activities",
                "db_table": "physical_activity",
                "indexes": [
                    models.Index(
                        fields=["major_heading"], name="physical_ac_major_h_c49cf4_idx"
                    ),
                    models.Index(
                        fields=["activity_description"],
                        name="physical_ac_activit_eb77ae_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AllergenDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitaa_app.allergen",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vitaa_app.dish"
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergen Dish",
                "verbose_name_plural": "Allergen Dishes",
                "db_table": "allergen_dish",
                "unique_together": {("dish", "allergen")},
            },
        ),
    ]
