# Generated by Django 5.2.5 on 2025-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitaa_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="allergen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="veg_class",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
