# Generated by Django 5.2.5 on 2025-08-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitaa_app", "0002_food_allergen_food_veg_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                ("allergen_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergen_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Allergen",
                "verbose_name_plural": "Allergens",
                "db_table": "allergen",
            },
        ),
        migrations.CreateModel(
            name="AllergenDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitaa_app.allergen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergen Dish",
                "verbose_name_plural": "Allergen Dishes",
                "db_table": "allergen_dish",
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("dish_id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_name", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("ingredients", models.CharField(max_length=255)),
                ("veg_class", models.CharField(max_length=255)),
                ("fat_g", models.DecimalField(decimal_places=1, max_digits=7)),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=7)),
                ("carbohydrate_g", models.DecimalField(decimal_places=1, max_digits=7)),
                ("calories_kcal", models.IntegerField()),
            ],
            options={
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
                "db_table": "dish",
                "unique_together": {("dish_name", "image_url")},
            },
        ),
        migrations.DeleteModel(
            name="Food",
        ),
        migrations.AddField(
            model_name="allergendish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vitaa_app.dish"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="allergendish",
            unique_together={("dish", "allergen")},
        ),
    ]
