# Generated by Django 5.2.5 on 2025-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaa_app', '0003_allergen_allergendish_dish_delete_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_ms_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_vi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_zh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
