# Generated by Django 5.2.5 on 2025-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaa_app', '0003_allergen_allergendish_dish_delete_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_heading', models.CharField(max_length=200)),
                ('major_heading_ms', models.CharField(blank=True, max_length=200)),
                ('major_heading_cn', models.CharField(blank=True, max_length=200)),
                ('major_heading_vn', models.CharField(blank=True, max_length=200)),
                ('activity_code', models.IntegerField(db_index=True, unique=True)),
                ('met_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_description_ms', models.CharField(blank=True, max_length=500)),
                ('activity_description_cn', models.CharField(blank=True, max_length=500)),
                ('activity_description_vn', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Physical Activity',
                'verbose_name_plural': 'Physical Activities',
                'db_table': 'physical_activity',
                'indexes': [models.Index(fields=['major_heading'], name='physical_ac_major_h_c49cf4_idx'), models.Index(fields=['activity_description'], name='physical_ac_activit_eb77ae_idx')],
            },
        ),
    ]
