# Generated by Django 5.2.5 on 2025-09-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaa_app', '0004_physicalactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_ms_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_vi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_zh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
