# Generated by Django 5.2.5 on 2025-09-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitaa_app', '0004_dish_dish_ms_name_dish_dish_vi_name_and_more'),
        ('vitaa_app', '0005_dish_dish_ms_name_dish_dish_vi_name_and_more'),
    ]

    operations = [
    ]
