# Generated by Django 5.2.5 on 2025-09-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaa_app', '0006_merge_20250917_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCDDeathStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=128)),
                ('cause', models.CharField(db_index=True, max_length=256)),
                ('number_of_deaths', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_of_deaths', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'db_table': 'ncd_death_stat',
                'indexes': [models.Index(fields=['year', 'location'], name='ncd_death_s_year_5d058f_idx'), models.Index(fields=['location', 'cause'], name='ncd_death_s_locatio_2f3a64_idx')],
                'unique_together': {('year', 'location', 'cause')},
            },
        ),
    ]
